const products = [
  {
    id: 1,
    img: '../img/tops1.jpg',
    name: 'apartment department : Mock Neck Volume Sleeve Pullover',
    price: '53.9',
  },
  {
    id: 2,
    img: '../img/tops2.jpg',
    name: 'apartment department : Mock Neck Volume Sleeve Pullover',
    price: '53.9',
  },
  {
    id: 3,
    img: '../img/tops2-1.jpg',
    name: 'zootie : Embroidered Brushed Lace Mellow High-Neck Top',
    price: '19.99',
  },
  {
    id: 4,
    img: '../img/tops2-2.jpg',
    name: 'zootie : Embroidered Brushed Lace Mellow High-Neck Top',
    price: '19.99',
  },
  {
    id: 5,
    img: '../img/tops3-1.jpg',
    name: 'Faux Leather Riders Jacket [Double]',
    price: '49.9',
  },
  {
    id: 6,
    img: '../img/tops3-2.jpg',
    name: 'Faux Leather Riders Jacket [Double]',
    price: '49.9',
  },
  {
    id: 7,
    img: '../img/bottom2-1.jpg',
    name: 'zootie : Heavyweight chino straight pants',
    price: '39.9',
  },
  {
    id: 8,
    img: '../img/bottom2-2.jpg',
    name: 'zootie : Heavyweight chino straight pants',
    price: '39.9',
  },
  {
    id: 9,
    img: '../img/bottom2-3.jpg',
    name: 'zootie : Heavyweight chino straight pants',
    price: '39.9',
  },
  {
    id: 10,
    img: '../img/bottom2-4.jpg',
    name: 'zootie : Heavyweight chino straight pants',
    price: '39.9',
  },
  {
    id: 11,
    img: '../img/bottom3-1.jpg',
    name: 'zootie: Air Pants',
    price: '39.9',
  },
  {
    id: 12,
    img: '../img/bottom3-2.jpg',
    name: 'zootie: Air Pants',
    price: '39.9',
  },
  {
    id: 13,
    img: '../img/bottom3-3.jpg',
    name: 'zootie: Air Pants',
    price: '39.9',
  },
  {
    id: 14,
    img: '../img/bottom2.jpg',
    name: 'zootie: Heavyweight Chino Loose Tapered Pants',
    price: '39.9',
  },
  {
    id: 15,
    img: '../img/bottom4.jpg',
    name: 'zootie: Heavyweight Chino Loose Tapered Pants',
    price: '39.9',
  },
];
